// this file generated automatically. don't edit by hand, silly

locblurb = {
  bamp: "  <p>A little plaza sits on the northwest corner of Oxford &amp; Addison.\n    A short metal fence bounds this plaza's south side, preventing the\n    careless from tumbling into a sunken parking lot.\n\n  <p>Consider this fence. You might expect its pickets to interfere with its\n    frequency, reduce it to rattles. But if you rap one of its horizontal\n    spans with a knuckle, it vibrates truly. What craft it must require to\n    join these pieces so well that they move as one?\n\n  <p>When you are done, look north to answer the question:\n    In case of a fire alarm, who should you call? _&nbsp;_&nbsp;_&nbsp;_\n",
  brow: "  <p>At 2150 Allston Way (between Shattuck and Oxford), a metal fence\n    protects a bike parking area. Its design suggests a sound wave (or\n    perhaps a domino mask).\n\n  <p>Tap a few of the fence's slats. Each slat's vibration is impressive,\n    no matter whether its \"twist\" is short or long. One wonders how the\n    frequency of such a slat would compare to a similarly-sized twist of\n    metal <em>fusilli</em>.\n\n  <p>When you are done, enter the word that fills in the blank:\n    This _&nbsp;_&nbsp;_&nbsp;_ is monitored by security cameras.\n",
  clok: "  <p>On the south side of Shattuck Avenue a few paces south of Allston Way,\n    a clock measures time and announces it to all people within view.\n    \"Civic time\" is a curious thing: its worth is not in its accuracy or\n    precision, but in how useful it is to members of a society who\n    want to synchronize with each other.\n\n  <p>Throughout history, we haven't just learned to measure time. We've\n    learned to agree on \"what time it is.\" Our ancestors announced changes\n    of the watch with bells, with horns, with klaxons. We invented calendars,\n    leap years, clocks, time zones, digital watches, and daylight savings\n    time all so that friends can plan a get-together as easily as saying\n    \"Let's meet at noon on the 6th for lunch.\"\n    \n  <p>When you are done, look west to answer the question:\n    What kind of station are you next to? _&nbsp;_&nbsp;_&nbsp;_\n",
  colg: "  <p>At 2050 Center Street, west of Shattuck Ave, is Berkeley City College.\n    Enter the building and walk up a few steps to the atrium.\n    Consider the low barrier that preserves you from tumbling into the basement.\n\n  <p>Here we see an example of <em>weave</em>, a concept dear to the society.\n    Notice how adjacent fence slats' \"waves\" have the same frequency but\n    are out of phase. You might think this difference would prevent them\n    from forming a structure, but its these differences that hold them\n    together.\n\n  <p>When you are done, look at a plaque by the library door to find\n    the word that fills in the blank: \"Her unshakable commitment\n    helped _&nbsp;_&nbsp;_&nbsp;_&hellip;\"\n",
  drum: "  <p>On the North side of this park is a little fenced in section\n    with some labeled column-tops and some low cylinders that are\n    maybe supposed to be drums? Which seems like something we could\n    use? But the drum tops are these pieces of metal that I couldn't\n    get good sounds out of? So I'm not even that certain that these\n    are supposed to be drums? I dunno. If you have any brilliant ideas,\n    don't be shy about 'em.\n\n  <p>Meanwhile, the way to knock this one off your checklist is to\n    enter IDEA.\n",
  fork: "  <p>At the island in the center of the intersection of Shattuck and Center\n    is a giant tuning fork. Walk up to it. (Watch for traffic, of course.)\n\n  <p>This tuning fork, titled Free Oscillation of the Earth, is a sort of\n    tribute to the vibrational frequency of the earth.\n    The earth's frequency is low, so low that we\n    don't feel its movement as a vibration. We can measure it, we can\n    reason about it; but when you stand on the earth's surface, there's\n    feel of rumbling (unless, perhaps, a BART train passes under).\n    Yet the earth connects us all; if we could feel its vibrations, it\n    would be a rare shared experience.\n  \n  <p>When you are done, look at a plaque to find the last source of\n    random vibrations (before the \"etc\") and enter it.\n",
  pasg: "  <p>Arts Passage, Center Street, west of Shattuck Ave.\n\n  <p>Hey playtesters/collaborators/folks, this here is another spot\n    I'm not sure what (if anything) to do with.\n\n  <p>Waves on ceiling. But they aren't sound waves. They're sound-baffling\n    waves. Uhm, I got nuthin'. It's kind of a neat spot, though. Maybe\n    someone has a better idea of what to do with it?\n\n  <p>Meanwhile, the way to knock this one off your checklist is to\n    enter ARTS.\n",
  plnt: "  <p>Allston Place is a little courtyard off of Allston Way, a little\n    west of Oxford St.\n\n  <p>Hey playtesters/collaborators/folks, this here is another spot\n    I'm not sure what (if anything) to do with.\n\n  <p>There's a wavy bench? That's a sort of waveform. Maybe we could\n    put something in a planter? They seem kind of neglected, so maybe\n    things would stay in them?\n\n  <p>Meanwhile, the way to knock this one off your checklist is to\n    enter MAIN.\n",
  poem: "  <p>On Addison Street west of Shattuck Avenue near a recessed gray\n    door signed \"PRIVATE PROPERTY\" on the floor is a poem titled\n    \"The World\".\n\n  <p>We think of resonant frequencies as sounds; a poet might evoke\n    a similar phenomenon with words. This poem talks about music and\n    silence passing thoughts and feelings from one person to another.\n    And of course if we pause to understand the poem, it passes\n    thoughts and feelings from the poet to us.\n\n  <p>When you are done, look at the poem to find the name of a\n    resonating musical instrument and enter it.\n",
  vine: "  <p>It's Trumpetvine Court, a courtyard between Jupiter and\n    Cafe Panini.\n\n  <p>Hey playtesters/collaborators/folks, this here is another spot\n    I'm not sure what (if anything) to do with.\n    \n  <p>When I was here, there was music playing on speakers? But I don't\n    know when there's music playing? Always? Sometimes? There's neat\n    art around, but I never came up with a frequency/resonance/whatever\n    thing to say about it?\n    \n  <p>Meanwhile, the way to knock this one off your checklist is to\n    enter MUSE.\n",

}
