// this file generated automatically. don't edit by hand, silly

locblurb = {
  bamp: "  <p>A little plaza sits on the northwest corner of Oxford &amp; Addison.\n    A short metal fence bounds this plaza's south side, preventing the\n    careless from tumbling into a sunken parking lot.\n\n  <p>Consider this fence. You might expect its pickets to interfere with its\n    frequency, reduce it to rattles. But if you rap one of its horizontal\n    spans with a knuckle, it vibrates truly. What craft it must require to\n    join these pieces so well that they move as one?\n\n  <p>When you are done, look north to answer the question:\n    What one or two words occur to you?\n",
  brow: "  <p>At 2150 Allston Way (between Shattuck and Oxford), a metal fence\n    protects a bike parking area. Its design suggests a sound wave (or\n    perhaps a domino mask).\n\n  <p>In the society, we heed the notion of <em>resonance</em>. An object\n    can have a resonant frequency, one that makes it vibrate wholly.\n    When joined in a suitable medium, one object can transmit vibrations\n    to another. When two similar objects have the same resonant frequency,\n    these transmissions can be especially notable.\n\n  <p>Tap a few of the fence's slats; a slat's center is an especially\n    good place to tap. Each slat's vibration is impressive,\n    no matter whether its \"twist\" is short or long. One wonders how the\n    frequency of such a slat would compare to a similarly-sized twist of\n    metal <em>fusilli</em>.\n\n  <p>When you are done, consider the something or other.\n    What one or two words occur to you?\n",
  clok: "  <p>On the west side of Shattuck Avenue a few paces south of Allston Way,\n    a clock measures time and announces it to all people within view.\n    \"Civic time\" is a curious thing: its worth is not in its accuracy or\n    precision, but in how useful it is to members of a society who\n    want to synchronize with each other.\n\n  <p>Throughout history, we haven't just learned to measure time. We've\n    learned to agree on \"what time it is.\" Our ancestors announced changes\n    of the watch with bells, with horns, with klaxons. We invented calendars,\n    leap years, clocks, time zones, digital watches, and daylight savings\n    time all so that friends can plan a get-together as easily as saying\n    \"Let's meet at noon on the 6th for lunch.\"\n    \n  <p>When you are done, look west to answer the question:\n    What one or two words sustain the yadda yadda?\n",
  colg: "  <p>At 2050 Center Street, east of Milvia, is Berkeley City College.\n    Enter the building and walk up some steps to the atrium.\n    Consider the low barrier that preserves careless folks\n    from tumbling into the basement.\n\n  <p>Here we see an example of <em>weave</em>, a concept dear to the society.\n    Notice how adjacent fence slats' \"waves\" have the same frequency but\n    are out of phase. You might think this difference would prevent them\n    from forming a structure, but its these differences that hold them\n    together.\n\n  <p>When you are done, enter a couple of words that <em>oh gee whiz something\n    to do with the concept of weave I guess</em>.\n",
  fork: "  <p>At the island in the center of the intersection of Shattuck and Center\n    looms a giant tuning fork. Walk up to it. (Watch for traffic, of course.)\n\n  <p>This tuning fork, titled Free Oscillation of the Earth, is a sort of\n    tribute to the vibrational frequency of the earth.\n    The earth's frequency is low, so low that we\n    don't feel its movement as a vibration. We can measure it, we can\n    reason about it; but when you stand on the earth's surface, there's\n    feel of rumbling (unless, perhaps, a BART train passes under).\n    Yet the earth connects us all; if we could feel its vibrations, it\n    would be a rare shared experience.\n\n  <p>Follow the directions TO SAMPLE THE EARTH SONG. THE EARTH SONG may be\n    imperceptable. If that disappoints you (or even if it doesn't),\n    you might try knocking on a few other bits of the fork you can reach.\n  \n  <p>When you are done, enter a couple of words or whatever.\n",
  pasg: "  <p>Arts Passage, Center Street, west of Shattuck Ave.\n\n  <p>Hey playtesters/collaborators/folks, this here is another spot\n    I'm not sure what (if anything) to do with.\n\n  <p>Waves on ceiling. But they aren't sound waves. They're sound-baffling\n    waves. Uhm, I got nuthin'. It's kind of a neat spot, though. Maybe\n    someone has a better idea of what to do with it?\n\n  <p>Meanwhile, the way to knock this one off your checklist is to\n    enter a couple of words.\n",
  poem: "  <p>On the south side of Addison Street\n    west of Shattuck Avenue, there is a recessed gray\n    door under a black and orange sign marking \"PRIVATE PROPERTY\".\n    Before that door, on the ground sits a poem titled \"The World\".\n    It <i>is</i> on the sidewalk but does <i>not</li> look like this\n    interesting ear-wave sidewalk thingy.\n\n  <p>We think of resonant frequencies as sounds; a poet might evoke\n    a similar phenomenon with words. This poem talks about music and\n    silence passing thoughts and feelings from one person to another.\n    And of course if we pause to understand the poem, it passes\n    thoughts and feelings from the poet to us.\n\n  <p>Read this poem aloud. Some of its words resound; others crackle and snap.\n    Reflect on the poet's choices.\n\n  <p>When you are done, enter a couple of words. Bonus points if they\n    rhyme. Double bonus points if they don't. There are no rules in poetry.\n",
  vine: "  <p>It's Trumpetvine Court, a courtyard between Jupiter and\n    Cafe Panini.\n\n  <p>Hey playtesters/collaborators/folks, this here is another spot\n    I'm not sure what (if anything) to do with.\n    \n  <p>When I was here, there was music playing on speakers? But I don't\n    know when there's music playing? Always? Sometimes? There's neat\n    art around, but I never came up with a frequency/resonance/whatever\n    thing to say about it?\n    \n  <p>Anyhow, enter a couple of words or something.\n",

}
